from feedgen.compat import string_types as string_types
from feedgen.util import ensure_format as ensure_format
from feedgen.util import formatRFC2822 as formatRFC2822
from feedgen.util import xml_elem as xml_elem
from feedgen.util import xml_fromstring as xml_fromstring

class FeedEntry:
    def __init__(self) -> None: ...
    def atom_entry(self, extensions: bool = True): ...
    def rss_entry(self, extensions: bool = True): ...
    def title(self, title: str | None = None) -> None: ...
    def id(self, id=None): ...
    def guid(self, guid: str | None = None, permalink: bool = False) -> None: ...
    def updated(self, updated=None): ...
    def author(self, author=None, replace: bool = False, **kwargs): ...
    def content(self, content=None, src=None, type=None): ...
    def link(
        self,
        link: str | None = None,
        replace: bool = False,
        href: str | None = None,
        rel: str | None = None,
    ) -> None: ...
    def summary(self, summary=None, type=None): ...
    def description(
        self, description: str | None = None, isSummary: bool = False
    ) -> None: ...
    def category(self, category=None, replace: bool = False, **kwargs): ...
    def contributor(self, contributor=None, replace: bool = False, **kwargs): ...
    def published(self, published=None): ...
    def pubDate(self, pubDate=None): ...
    def pubdate(self, pubDate=None): ...
    def rights(self, rights=None): ...
    def comments(self, comments=None): ...
    def source(self, url=None, title=None): ...
    def enclosure(self, url=None, length=None, type=None): ...
    def ttl(self, ttl=None): ...
    def load_extension(self, name, atom: bool = True, rss: bool = True) -> None: ...
    def register_extension(
        self, namespace, extension_class_entry=None, atom: bool = True, rss: bool = True
    ) -> None: ...
