from feedgen.compat import string_types as string_types
from feedgen.entry import FeedEntry as FeedEntry
from feedgen.util import ensure_format as ensure_format
from feedgen.util import formatRFC2822 as formatRFC2822
from feedgen.util import xml_elem as xml_elem

class FeedGenerator:
    def __init__(self) -> None: ...
    def atom_str(
        self,
        pretty: bool = False,
        extensions: bool = True,
        encoding: str = "UTF-8",
        xml_declaration: bool = True,
    ): ...
    def atom_file(
        self,
        filename,
        extensions: bool = True,
        pretty: bool = False,
        encoding: str = "UTF-8",
        xml_declaration: bool = True,
    ) -> None: ...
    def rss_str(
        self,
        pretty: bool = False,
        extensions: bool = True,
        encoding: str = "UTF-8",
        xml_declaration: bool = True,
    ) -> str: ...
    def rss_file(
        self,
        filename,
        extensions: bool = True,
        pretty: bool = False,
        encoding: str = "UTF-8",
        xml_declaration: bool = True,
    ) -> None: ...
    def title(self, title: str | None = None) -> None: ...
    def id(self, id: str | None = None) -> None: ...
    def updated(self, updated=None): ...
    def lastBuildDate(self, lastBuildDate=None): ...
    def author(self, author=None, replace: bool = False, **kwargs): ...
    def link(
        self,
        link: str | None = None,
        replace: bool = False,
        href: str | None = None,
        rel: str | None = None,
    ) -> None: ...
    def category(self, category=None, replace: bool = False, **kwargs): ...
    def cloud(
        self, domain=None, port=None, path=None, registerProcedure=None, protocol=None
    ): ...
    def contributor(self, contributor=None, replace: bool = False, **kwargs): ...
    def generator(self, generator=None, version=None, uri=None): ...
    def icon(self, icon=None): ...
    def logo(self, logo=None): ...
    def image(
        self, url=None, title=None, link=None, width=None, height=None, description=None
    ): ...
    def rights(self, rights=None): ...
    def copyright(self, copyright=None): ...
    def subtitle(self, subtitle=None): ...
    def description(self, description: str | None = None) -> None: ...
    def docs(self, docs=None): ...
    def language(self, language=None): ...
    def managingEditor(self, managingEditor=None): ...
    def pubDate(self, pubDate=None): ...
    def rating(self, rating=None): ...
    def skipHours(self, hours=None, replace: bool = False): ...
    def skipDays(self, days=None, replace: bool = False): ...
    def textInput(self, title=None, description=None, name=None, link=None): ...
    def ttl(self, ttl=None): ...
    def webMaster(self, webMaster=None): ...
    def add_entry(
        self, feedEntry: FeedEntry | None = None, order: str = "prepend"
    ) -> FeedEntry: ...
    def add_item(self, item=None): ...
    def entry(self, entry=None, replace: bool = False): ...
    def item(self, item=None, replace: bool = False): ...
    def remove_entry(self, entry) -> None: ...
    def remove_item(self, item) -> None: ...
    def load_extension(self, name, atom: bool = True, rss: bool = True) -> None: ...
    def register_extension(
        self,
        namespace,
        extension_class_feed=None,
        extension_class_entry=None,
        atom: bool = True,
        rss: bool = True,
    ) -> None: ...
