from _typeshed import Incomplete

parser: Incomplete

def xml_fromstring(xmlstring): ...
def xml_elem(name, parent=None, **kwargs): ...
def ensure_format(val, allowed, required, allowed_values=None, defaults=None): ...
def formatRFC2822(date): ...
