"""add id and make date_posted nullable

Revision ID: 4f58139edcbf
Revises: 88e24b8af90e
Create Date: 2026-02-26 19:44:55.386754

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "4f58139edcbf"
down_revision: Union[str, Sequence[str], None] = "88e24b8af90e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item", sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )

    # Use batch operations for SQLite compatibility when altering columns
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("date_posted", existing_type=sa.DATETIME(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch operations for SQLite compatibility when altering columns
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.alter_column(
            "date_posted", existing_type=sa.DATETIME(), nullable=False
        )
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=False)

    op.drop_column("item", "id")
    # ### end Alembic commands ###
