"""add source column to item table

Revision ID: 88e24b8af90e
Revises:
Create Date: 2026-02-26 16:35:44.011259

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "88e24b8af90e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item",
        sa.Column(
            "source",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="unknown",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("item", "source")
    # ### end Alembic commands ###
