from feedgen.ext.base import BaseExtension as BaseExtension
from feedgen.util import xml_elem as xml_elem

class DcBaseExtension(BaseExtension):
    def __init__(self) -> None: ...
    def extend_ns(self): ...
    def extend_atom(self, atom_feed): ...
    def extend_rss(self, rss_feed): ...
    def dc_contributor(self, contributor=None, replace: bool = False): ...
    def dc_coverage(self, coverage=None, replace: bool = True): ...
    def dc_creator(self, creator=None, replace: bool = False): ...
    def dc_date(self, date=None, replace: bool = True): ...
    def dc_description(self, description=None, replace: bool = True): ...
    def dc_format(self, format=None, replace: bool = True): ...
    def dc_identifier(self, identifier=None, replace: bool = True): ...
    def dc_language(self, language=None, replace: bool = True): ...
    def dc_publisher(self, publisher=None, replace: bool = False): ...
    def dc_relation(self, relation=None, replace: bool = False): ...
    def dc_rights(self, rights=None, replace: bool = False): ...
    def dc_source(self, source=None, replace: bool = False): ...
    def dc_subject(self, subject=None, replace: bool = False): ...
    def dc_title(self, title=None, replace: bool = True): ...
    def dc_type(self, type=None, replace: bool = False): ...

class DcExtension(DcBaseExtension): ...

class DcEntryExtension(DcBaseExtension):
    def extend_atom(self, entry): ...
    def extend_rss(self, item): ...
