from _typeshed import Incomplete
from feedgen.ext.base import BaseEntryExtension as BaseEntryExtension
from feedgen.util import xml_elem as xml_elem

class GeoRSSPolygonInteriorWarning(Warning):
    geom: Incomplete
    def __init__(self, geom, *args, **kwargs) -> None: ...

class GeoRSSGeometryError(ValueError):
    geom: Incomplete
    def __init__(self, geom, *args, **kwargs) -> None: ...

class GeoEntryExtension(BaseEntryExtension):
    def __init__(self) -> None: ...
    def extend_file(self, entry): ...
    def extend_rss(self, entry): ...
    def extend_atom(self, entry): ...
    def point(self, point=None): ...
    def line(self, line=None): ...
    def polygon(self, polygon=None): ...
    def box(self, box=None): ...
    def featuretypetag(self, featuretypetag=None): ...
    def relationshiptag(self, relationshiptag=None): ...
    def featurename(self, featurename=None): ...
    def elev(self, elev=None): ...
    def floor(self, floor=None): ...
    def radius(self, radius=None): ...
    def geom_from_geo_interface(self, geom): ...
