from feedgen.ext.base import BaseEntryExtension as BaseEntryExtension, BaseExtension as BaseExtension
from feedgen.util import ensure_format as ensure_format, xml_elem as xml_elem

MEDIA_NS: str

class MediaExtension(BaseExtension):
    def extend_ns(self): ...

class MediaEntryExtension(BaseEntryExtension):
    def __init__(self) -> None: ...
    def extend_atom(self, entry): ...
    def extend_rss(self, item): ...
    def content(self, content=None, replace: bool = False, group: str = 'default', **kwargs): ...
    def thumbnail(self, thumbnail=None, replace: bool = False, group: str = 'default', **kwargs): ...
