from feedgen.ext.base import BaseEntryExtension as BaseEntryExtension
from feedgen.util import xml_elem as xml_elem

class PodcastEntryExtension(BaseEntryExtension):
    def __init__(self) -> None: ...
    def extend_rss(self, entry): ...
    def itunes_author(self, itunes_author=None): ...
    def itunes_block(self, itunes_block=None): ...
    def itunes_image(self, itunes_image=None): ...
    def itunes_duration(self, itunes_duration=None): ...
    def itunes_explicit(self, itunes_explicit=None): ...
    def itunes_is_closed_captioned(self, itunes_is_closed_captioned=None): ...
    def itunes_order(self, itunes_order=None): ...
    def itunes_subtitle(self, itunes_subtitle=None): ...
    def itunes_summary(self, itunes_summary=None): ...
    def itunes_season(self, itunes_season=None): ...
    def itunes_episode(self, itunes_episode=None): ...
    def itunes_title(self, itunes_title=None): ...
    def itunes_episode_type(self, itunes_episode_type=None): ...
