from feedgen.compat import string_types as string_types
from feedgen.ext.base import BaseExtension as BaseExtension
from feedgen.util import ensure_format as ensure_format, xml_elem as xml_elem

class PodcastExtension(BaseExtension):
    def __init__(self) -> None: ...
    def extend_ns(self): ...
    def extend_rss(self, rss_feed): ...
    def itunes_author(self, itunes_author=None): ...
    def itunes_block(self, itunes_block=None): ...
    def itunes_category(self, itunes_category=None, replace: bool = False, **kwargs): ...
    def itunes_image(self, itunes_image=None): ...
    def itunes_explicit(self, itunes_explicit=None): ...
    def itunes_complete(self, itunes_complete=None): ...
    def itunes_new_feed_url(self, itunes_new_feed_url=None): ...
    def itunes_owner(self, name=None, email=None): ...
    def itunes_subtitle(self, itunes_subtitle=None): ...
    def itunes_summary(self, itunes_summary=None): ...
    def itunes_type(self, itunes_type=None): ...
