from _typeshed import Incomplete
from feedgen.ext.base import BaseExtension as BaseExtension
from feedgen.util import xml_elem as xml_elem

SYNDICATION_NS: str
PERIOD_TYPE: Incomplete

class SyndicationExtension(BaseExtension):
    def __init__(self) -> None: ...
    def extend_ns(self): ...
    def extend_rss(self, rss_feed) -> None: ...
    def update_period(self, value): ...
    def update_frequency(self, value): ...
    def update_base(self, value): ...

class SyndicationEntryExtension(BaseExtension): ...
