from feedgen.ext.base import BaseEntryExtension as BaseEntryExtension, BaseExtension as BaseExtension
from feedgen.util import xml_elem as xml_elem

TORRENT_NS: str

class TorrentExtension(BaseExtension):
    def extend_ns(self): ...

class TorrentEntryExtension(BaseEntryExtension):
    def __init__(self) -> None: ...
    def extend_rss(self, entry) -> None: ...
    def filename(self, torrent_filename=None): ...
    def infohash(self, torrent_infohash=None): ...
    def contentlength(self, torrent_contentlength=None): ...
    def seeds(self, torrent_seeds=None): ...
    def peers(self, torrent_peers=None): ...
    def verified(self, torrent_verified=None): ...
